
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int notacionj = 9;
  public static final int c_conjuntoER = 15;
  public static final int allave = 2;
  public static final int porcentajes = 12;
  public static final int especial_conjER = 16;
  public static final int pcoma = 11;
  public static final int notacionj2 = 10;
  public static final int or = 21;
  public static final int resta = 7;
  public static final int cllave = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int asterisco = 20;
  public static final int id_conjuntoER = 14;
  public static final int interrogacion = 19;
  public static final int suma = 17;
  public static final int nombres = 5;
  public static final int concatenacion = 18;
  public static final int id_conj = 8;
  public static final int cadenarevi2 = 13;
  public static final int dospuntos = 4;
  public static final int mayor = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "allave",
  "cllave",
  "dospuntos",
  "nombres",
  "mayor",
  "resta",
  "id_conj",
  "notacionj",
  "notacionj2",
  "pcoma",
  "porcentajes",
  "cadenarevi2",
  "id_conjuntoER",
  "c_conjuntoER",
  "especial_conjER",
  "suma",
  "concatenacion",
  "interrogacion",
  "asterisco",
  "or"
  };
}

